/* ex: set ro ft=c: -*- buffer-read-only: t -*-
   !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
   This file is built by regen_perly.pl from perly.y.
   Any changes made here will be lost!
 */

#define PERL_BISON_VERSION  20003

#ifdef PERL_CORE
/* A Bison parser, made by GNU Bison 2.3.  */

/* Skeleton interface for Bison's Yacc-like parsers in C

   Copyright (C) 1984, 1989, 1990, 2000, 2001, 2002, 2003, 2004, 2005, 2006
   Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor,
   Boston, MA 02110-1301, USA.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* Tokens.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
   /* Put the tokens into the symbol table, so that GDB and other debuggers
      know about them.  */
   enum yytokentype {
     GRAMPROG = 258,
     GRAMEXPR = 259,
     GRAMBLOCK = 260,
     GRAMBARESTMT = 261,
     GRAMFULLSTMT = 262,
     GRAMSTMTSEQ = 263,
     BAREWORD = 264,
     METHOD = 265,
     FUNCMETH = 266,
     THING = 267,
     PMFUNC = 268,
     PRIVATEREF = 269,
     QWLIST = 270,
     FUNC0OP = 271,
     FUNC0SUB = 272,
     UNIOPSUB = 273,
     LSTOPSUB = 274,
     PLUGEXPR = 275,
     PLUGSTMT = 276,
     LABEL = 277,
     FORMAT = 278,
     SUB = 279,
     ANONSUB = 280,
     EXTERN = 281,
     PACKAGE = 282,
     USE = 283,
     WHILE = 284,
     UNTIL = 285,
     IF = 286,
     UNLESS = 287,
     ELSE = 288,
     ELSIF = 289,
     CONTINUE = 290,
     FOR = 291,
     GIVEN = 292,
     WHEN = 293,
     DEFAULT = 294,
     LOOPEX = 295,
     DOTDOT = 296,
     YADAYADA = 297,
     FUNC0 = 298,
     FUNC1 = 299,
     FUNC = 300,
     UNIOP = 301,
     LSTOP = 302,
     RELOP = 303,
     EQOP = 304,
     MULOP = 305,
     ADDOP = 306,
     DOLSHARP = 307,
     DO = 308,
     HASHBRACK = 309,
     NOAMP = 310,
     LOCAL = 311,
     MY = 312,
     REQUIRE = 313,
     COLONATTR = 314,
     FORMLBRACK = 315,
     FORMRBRACK = 316,
     PREC_LOW = 317,
     DOROP = 318,
     OROP = 319,
     ANDOP = 320,
     NOTOP = 321,
     ASSIGNOP = 322,
     DORDOR = 323,
     OROR = 324,
     ANDAND = 325,
     BITOROP = 326,
     BITANDOP = 327,
     SHIFTOP = 328,
     MATCHOP = 329,
     REFGEN = 330,
     UMINUS = 331,
     POWCOP = 332,
     POWOP = 333,
     POSTJOIN = 334,
     POSTDEC = 335,
     POSTINC = 336,
     PREDEC = 337,
     PREINC = 338,
     ARROW = 339
   };
#endif
/* Tokens.  */
#define GRAMPROG 258
#define GRAMEXPR 259
#define GRAMBLOCK 260
#define GRAMBARESTMT 261
#define GRAMFULLSTMT 262
#define GRAMSTMTSEQ 263
#define BAREWORD 264
#define METHOD 265
#define FUNCMETH 266
#define THING 267
#define PMFUNC 268
#define PRIVATEREF 269
#define QWLIST 270
#define FUNC0OP 271
#define FUNC0SUB 272
#define UNIOPSUB 273
#define LSTOPSUB 274
#define PLUGEXPR 275
#define PLUGSTMT 276
#define LABEL 277
#define FORMAT 278
#define SUB 279
#define ANONSUB 280
#define EXTERN 281
#define PACKAGE 282
#define USE 283
#define WHILE 284
#define UNTIL 285
#define IF 286
#define UNLESS 287
#define ELSE 288
#define ELSIF 289
#define CONTINUE 290
#define FOR 291
#define GIVEN 292
#define WHEN 293
#define DEFAULT 294
#define LOOPEX 295
#define DOTDOT 296
#define YADAYADA 297
#define FUNC0 298
#define FUNC1 299
#define FUNC 300
#define UNIOP 301
#define LSTOP 302
#define RELOP 303
#define EQOP 304
#define MULOP 305
#define ADDOP 306
#define DOLSHARP 307
#define DO 308
#define HASHBRACK 309
#define NOAMP 310
#define LOCAL 311
#define MY 312
#define REQUIRE 313
#define COLONATTR 314
#define FORMLBRACK 315
#define FORMRBRACK 316
#define PREC_LOW 317
#define DOROP 318
#define OROP 319
#define ANDOP 320
#define NOTOP 321
#define ASSIGNOP 322
#define DORDOR 323
#define OROR 324
#define ANDAND 325
#define BITOROP 326
#define BITANDOP 327
#define SHIFTOP 328
#define MATCHOP 329
#define REFGEN 330
#define UMINUS 331
#define POWCOP 332
#define POWOP 333
#define POSTJOIN 334
#define POSTDEC 335
#define POSTINC 336
#define PREDEC 337
#define PREINC 338
#define ARROW 339




#ifdef PERL_IN_TOKE_C
static bool
S_is_opval_token(int type) {
    switch (type) {
    case BAREWORD:
    case FUNC0OP:
    case FUNC0SUB:
    case FUNCMETH:
    case LSTOPSUB:
    case METHOD:
    case PLUGEXPR:
    case PLUGSTMT:
    case PMFUNC:
    case PRIVATEREF:
    case QWLIST:
    case THING:
    case UNIOPSUB:
	return 1;
    }
    return 0;
}
#endif /* PERL_IN_TOKE_C */
#endif /* PERL_CORE */
#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED
typedef union YYSTYPE
{
    I32	ival; /* __DEFAULT__ (marker for regen_perly.pl;
				must always be 1st union member) */
    char *pval;
    OP *opval;
    GV *gvval;
}
/* Line 1529 of yacc.c.  */
	YYSTYPE;
# define yystype YYSTYPE /* obsolescent; will be withdrawn */
# define YYSTYPE_IS_DECLARED 1
# define YYSTYPE_IS_TRIVIAL 1
#endif




#if YYDEBUG
#define YYPRINT
#endif

/* Generated from:
 * 54321253b58513cc4acbcff45b8df32bd68678beaa454594c5a9ace1db747df7 perly.y
 * d75acf04e5e050e9d0de13999b5b46a13f176dcf9f75c07acf51e913fc41db9a regen_perly.pl
 * ex: set ro: */
